version: "3.8"

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: FYBR
      POSTGRES_USER: FYBR
      POSTGRES_PASSWORD: FYBR
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local